### ISSUE TITLE
grammar problems

### ISSUE THREAD

**Issue by monolithpl** [pwrmind/VerbTensesTable#1]
hi, MAJOR problems here. perfect tenses are not `[have] + past simple` but `[have] + past participle`, which is another form you don't have included in your app!

```
 $scope.getPastPerfect = function (v) {
                return "had " + $scope.getPastSimple( v );
            } 
....
 $scope.getPresentPerfect = function (v) {
                return "have " + $scope.getPastSimple( v );
            }
....
            $scope.getFuturePerfect = function (v) {
                return "will have " + $scope.getPastSimple( v );
            } 
```

**Comment by pwrmind** [comment]
Thank you for your interest in my project! My English is not so good as yours :) I did this project to understand the word order in English, and the rules of sentence structure.

**Comment by monolithpl** [comment]
sure! i was looking for a project that changed verb tenses.
for some information, you can have a look here http://english-the-easy-way.com/Present_Tense/Present_Perfect_Tense_Chart.htm

**Comment by pwrmind** [comment]
This is your website?

**Comment by pwrmind** [comment]
"changed verb tenses" you mean verb conjunction? [http://conjugator.reverso.net/conjugation-english-verb-go.html](url)

**Comment by monolithpl** [comment]
yeah, conjugation :) no that's not me. i have a website at https://vocab.today but it is empty now. check back after the summer holidays. and good luck on your project!

**Comment by pwrmind** [comment]
Thanks! So, I may try do it for you, if you help me with grammar...

**Comment by monolithpl** [comment]
what kind of help do you need?
my project's completed - i was frustrated that the online lists of verbs were incomplete, so i compiled my own https://github.com/monolithpl/verb.forms.dictionary

**Comment by pwrmind** [comment]
https://pwrmind.github.io/VerbFinder/

**Comment by pwrmind** [comment]
you are English teacher, and I learning English :) You may experent your lesons on me

**Comment by monolithpl** [comment]
cool! i've looked at your source code and it's an interesting approach. honestly, because of so many English verbs sharing the same form with nouns, it's a difficult project. i'm not really happy with the results from my project, but for now that's ok.
and yes, i am an English teacher, but I don't teach online. maybe i should change my mind? which country are you living in now?

**Comment by pwrmind** [comment]
I'm from Russia. I live and work in Moscow. I'm a programmer. In my work very needed English language. But very difficult to learn without communication with native speaker.

**Comment by monolithpl** [comment]
cool! i lived in moscow for a year some time ago, i worked for bkc international house. i speak russian a little bit, too.
i understand your problem, with all the technology out there, you still need a human to talk to :)
and listen, it's a very interesting idea. i'm super busy until the end of the week (i've got a 40 git pushes to do) but perhaps we could meet for a few minutes on skype next week and you can tell me what you had in mind. that ok with you?

**Comment by pwrmind** [comment]
Wow! Cool! It's a very very cool! I really want to learn English. I would like to warn:
- I read and write with dictionary;
- I have horrible pronunciation;
- I have a very poor vocabulary;
- I have horrible grammar ( simple and continous little bit );
- I choose my words long;
If this is not a problem for you :) then I'll be glad to talk on Skype! skype: aleksey.babanov, e-mail: aleksey.babanov@icloud.com

**Comment by pwrmind** [comment]
https://pwrmind.github.io/VerbTensesTable/

**Comment by monolithpl** [comment]
great work on your verbTensesTable! works really well, and it's a tool that I will definitely recommend to my lower-level students!
my skype id is wiktor.jakubczyc but you'll see my skype request anyway. i should be online this evening so perhaps we can speak tonight

**Comment by pwrmind** [comment]
I added question and negative forms, and changed CSS https://pwrmind.github.io/VerbTensesTable/ check this out :)

**Comment by monolithpl** [comment]
how about adding passive voice too (just to make it 100% complete?)

**Comment by pwrmind** [comment]
I don't know yet how to make it. Because I don't know how to make it dynamicly. But I will think about it.

Where are you living now? What is the difference between our time? Are you working at night?

**Comment by pwrmind** [comment]
Can you check passive voice, please? https://pwrmind.github.io/VerbTensesTable/
